### ISSUE TITLE
Simple sample?

### ISSUE THREAD

**Issue by mikevbaker** [techniq/react-odata#2]
I'm trying to construct the simplest of samples just to see if I can use react-odata in my app. For some reason the list doesn't get built. The odata service is working, I can get data by entering the url in the browser and it's working in other apps I've made in ionic and other frameworks. 

```
import React, { Component } from 'react';
import {
   Text,
   View,
   ScrollView
} from 'react-native';
import { List, ListItem } from 'react-native-elements';
import OData from 'react-odata';const baseUrl = 'http://ODATAURL/odata/Products';
const query = false;
<OData baseUrl={baseUrl} query={query}>
    {({ loading, error, data }) => (
        <View style={{ height: 400 }}>
            <Text>HI THERE!</Text>
            {loading && <Text>Loading...</Text>}
            {error && <Text>error...</Text>}
            {data &&
                <List>
                    {data.map((product) => (
                        <ListItem
                            key={product.ProductId}
                            title={`${product.ItemCode}`}
                        />
                    ))}
                </List>
            }
            </View>
        )}
</OData>
`````

I see the text that says HI THERE. But nothing else. I even tried putting in some sample list items but they didn't show up either. Can somebody help out with this? Is this the right way to handle the return data? Would is be possible for someone to add an example to the repo?

Thanks,
Mike

**Comment by techniq** [comment]
I'm away from my computer right now, but it looks like your query being
false is the issue. You either need to not pass query or pass an empty
object to fetch all, or construct a query object with filter, etc (see my
odata-query project for more details).

**Comment by mikevbaker** [comment]
I tried query = {} and I tried query = { filter: ProductId: 1 } and I tried { filter: ProductId: '1' }. I believe I also tried leaving the query param out, and setting it to null but I got syntax errors or exception.
After trying those things I dug into the odata.js file and I saw the item being tested this.props.query !== false on line 86. So that's why I'm trying it that way.
I'm beginning to think it's something to do with the asynchronous nature and I need to make the list build after the return? I'll check out your odata-query project to see if I can follow it. I'm a veteran programmer... in C++ so I'm a bit out of my element here.

**Comment by techniq** [comment]
@mikevbaker No worries.  I just noticed it looks like you are using react-native, which should be fine, but I haven't tested there yet.  Ultimately react-odata using [odata-query](https://github.com/techniq/odata-query) and [react-fetch-component](https://github.com/techniq/react-fetch-component) under the hood, the late uses `window.fetch` to issue the actual requests (unless overridden in the `fetchFunction` prop).

With that said:

- Can you past a know good request (using `curl` or just the browse)?  For example, are you just hitting `http://ODATAURL/odata/Products`.  I'm assuming ODATAURL is actually `localhost:5000` or something.
- Whare you using for the backend?  https://github.com/OData/WebApi?

**Comment by mikevbaker** [comment]
ODATAURL isn't localhost, it's an odata service I wrote in C# and posted to AWS Elastic Beanstalk for testing. I've been using it for testing other apps that I'm learning, MVC Razor, ionic framework. The service is working and I can see the result if I create a separate fetch request in the componentWillMount function. (I'm using react-native run-android to get it started then I used the developer menu to start remote JS debugging so I can have breakpoints)
I can try one of the sample services at odata.org... https://services.odata.org/TripPinRESTierService/People

I created this project using react-native init. I'm in the process of creating a new one with create-react-native-app to see if I have better luck with that. I will be wanting to build apps that I can publish in the app store and play store which is why I'm trying react-native init.

**Comment by techniq** [comment]
Hmm, so is `ODATAURL` have an entry in your `hosts` file.  I'm not overly familiar with AWS Elastic Beanstalk but wasn't sure how something like `curl http://ODATAURL/odata/Products` was resolving, unless it was an environment variable (in that case, `ODATAURL` needs to be replaced) or had a host entry.  I know using docker compose it will add host entries for each container so maybe something similar is happening here.

I was trying to boil it down to it's essence to see where the problem lies.  I think it makes sense to try another endpoint like the you mentioned to rule out an issue there / configuration.

**Comment by mikevbaker** [comment]
No, I just posted ODATAURL so that the real URL wouldn't be in a public forum, I'd be happy to share it with you privately

**Comment by mikevbaker** [comment]
When I try using my url with const query = { filter: { ProductId: 1 } }; I get an error 
TyepError: In this environment the sources for assign MUST be an object. This error is a performance optimization and not spec compliant.
The error is located at :
in Fetch (create by OData)
in OData (at App.js:32) // where the <OData ... > declaration is in my render() function.

I get the same error trying these values:
const baseUrl = 'https://services.odata.org/TripPinRESTierService/People';
const query = { filter: { FisrtName: 'Russell' } };
The error goes away when I set query = false. But I still get no data :(

**Comment by techniq** [comment]
Hmm, a quick Google appears to reveal a react-native generated error. I
don't have much time to dig in right now to see how tofix or  work around
at the moment as I don't have a react native project at the moment.

Issue might be in react-fetch-component and not react-odata.

**Comment by mikevbaker** [comment]
Thanks for the help so far. I'm going to come back to this tomorrow or later in the week and I'll let you know how it goes.
